### ISSUE TITLE
level 3 granularity throws error: ParserError: Error tokenizing data. C error: out of memory

### ISSUE THREAD

**Issue by morrisseyj** [covid19datahub/Python#2]
I am trying to look at data at the granularity of level 3 but always run into this error: `ParserError: Error tokenizing data. C error: out of memory`.

Here is the code: 
```
from covid19dh import covid19
covid19('United Kingdom', 
       verbose = False, 
       level = 3, 
       start = '2020-06-01', end = '2020-06-02')

ParserError: Error tokenizing data. C error: out of memory
```
So even trying to get 2 days of data seems to make the data frame too large.  If I set `level = 2`, everything runs fine.

**Comment by eguidotti** [comment]
Hello @morrisseyj, thank you for your message.
Unfortuntely I cannot reproduce the issue as the code above is working on my laptop.
It seems the error is due to limited amount of memory. Also in case of just a couple of days of data, the package needs to process the whole dataset. Level 3 is quite resource intensive. Level 1 and 2 are much smaller.
You might want to download directly the datasets available [here](https://covid19datahub.io/articles/data.html) and optimize the processing based on your needs.

**Comment by morrisseyj** [comment]
Ok, thanks very much. This all makes sense. Will have a look at the data and see if I can do anything. 

Very much appreciate your work on this project.

**Comment by eguidotti** [comment]
Great @morrisseyj , thanks for your feedback!
